# Generated by Django 5.0.6 on 2024-06-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminData',
            fields=[
                ('Admin_ID', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=100)),
                ('Middle_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Last_Name', models.CharField(max_length=100)),
                ('User_Name', models.CharField(max_length=100)),
                ('Contact_Number', models.CharField(blank=True, max_length=100, null=True)),
                ('Image', models.ImageField(blank=True, default='default_image_path.jpg', null=True, upload_to='admin_images/')),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Admin_Data',
            },
        ),
        migrations.AddField(
            model_name='info',
            name='Image',
            field=models.ImageField(blank=True, default='default_image_path.jpg', null=True, upload_to='lmss/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='Book_Image',
            field=models.ImageField(blank=True, default='default_image_path.jpg', null=True, upload_to='lmsss/'),
        ),
    ]
