# Generated by Django 5.0.1 on 2024-02-24 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
    ]
