# Generated by Django 5.0.1 on 2024-02-29 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20240224_1024'),
    ]

    operations = [
    ]
